### ISSUE TITLE
V3 bed file has incorrect format

### ISSUE THREAD

**Issue by thanhleviet** [connor-lab/ncov2019-artic-nf#28]
In the V3 bed file, the 5th column does not have proper values as `ivar trim` expects. This could be easily fixed if we download and manually edit the bed file since @sb10 has added local input for the bed file, but if users choose download the github repo, the step trimPrimerSequences will crash...
@m-bull is it worth to add smth in `illuminaNcov,.nf` like 

```        
if (params.fixBed) {
          makeIvarBedfile(articDownloadScheme.out.scheme)
          makeIvarBedfile.out.bed.set {ch_bed}
        } else {
          articDownloadScheme.out.bed.set {ch_bed}
 }
```
or ask artic to fix the V3 bed file?

**Comment by m-bull** [comment]
My preference would be to get the bedfile fixed by artic as it doesn't follow the bed file specs. I've opened some communications to this end.

For now you can either specify `--bed` and `--ref`, or use a local version of the repo with your changes to the bedfile commited, using `--schemeRepoURL  file:///path/to/local/repo`.

**Comment by thanhleviet** [comment]
Thanks, might be good to reflect this in README?

**Comment by jackkamm** [comment]
Just wanted to note that as of version 1.2.2, `ivar trim` won't crash if an improper bed file is provided. It will just skip trimming which may cause undesired output. https://github.com/andersen-lab/ivar/issues/46

**Comment by m-bull** [comment]
This should be fixed in https://github.com/connor-lab/ncov2019-artic-nf/commit/bc9884de54445eeeb5a73cb2f50fc2f10c9f3b4a. Thanks for your help @will-rowe.
