### ISSUE TITLE
Synching with fieldbioinformatics

### ISSUE THREAD

**Issue by jts** [connor-lab/ncov2019-artic-nf#38]
Hi,

I noticed the environments are out of synch with the main fieldbioinformatics env (which has merged the nanopolish and medaka environments). Nanopolish has been updated a few times since 0.12.5 too and I'd like this repo to use the latest version. I don't mind sending a PR here when I update nanopolish but I'd prefer if I could just update fieldbioinformatics and have it propagate here - is this possible to set up?

Thanks,
Jared

**Comment by m-bull** [comment]
Hi @jts - I've literally been working on this this afternoon, will update to follow fieldbioinformatics master again which should propagate your PRs this way.

**Comment by jts** [comment]
Great, thank you!

**Comment by m-bull** [comment]
Deleted message above - I'll think of a cleverer way to grab the `environment.yml` files from fieldbioinformatics and push some updates this afteroon.

**Comment by m-bull** [comment]
Hi @jts - this took me longer than anticipated!

Because I need to pull in the fieldbioinformatics tools as a dependency, there's no simple way to do that from `environment.yml` in the fieldbioinformatics repo, as its not listed as a dependency of itself.

I've compromised on updating the Nanopore conda environment on the fly using `environment.yml` from https://github.com/artic-network/artic-ncov2019, as this is the environment/process described in the [ARTIC SOP](https://artic.network/ncov-2019/ncov2019-bioinformatics-sop.html), which I wanted to follow as closely as I could with this workflow. This environment pulls in all of the dependencies required for the fieldbioinformatics/artic tools, and fieldbioinfomatics itself, which covers everything the workflow needs. Hope this is acceptable!

Specific changes supporting this are in https://github.com/connor-lab/ncov2019-artic-nf/pull/39/commits/3a39f9c74f4bd9da57ad5cd46f48d240e81cb8c9.

**Comment by jts** [comment]
Thanks @m-bull, that looks good. Just to make sure I understand correctly, will it update `environment.yaml` every time nextflow is run?

If possible could you make the default nanopolish 0.13.2 anyway? I'll be making a PR against artic-ncov-2019 today.

**Comment by m-bull** [comment]
@jts - final comment on this, and properly fixed with https://github.com/connor-lab/ncov2019-artic-nf/commit/8b0f5ea06f94a8f7235613c20fc371c886f695b9.

This uses the `artic` package directly from `conda`, so will pull in whatever deps are defined there.
