### ISSUE TITLE
Oxford Nanpore data in pipeline

### ISSUE THREAD

**Issue by ctr26** [connor-lab/ncov2019-artic-nf#72]
I have for fastq.gz files that have been:

```
"The libraries were generated using the native barcode kits from Nanopore"
"Raw data was demultiplexed, amplicon primers were trimmed and human data was removed by mapping against the human reference genome."
```

But they don't come with fast5 files. If I don't provided a "--fast5-directory" directory then the pipeline fails at "articMinIONNanopolish" as it tries to name a folder as "false". Are the fast5 files not as optional the help guide claims?

Best

Craig

**Comment by m-bull** [comment]
Hi @ctr26 - as nanopolish requires signal level data, you'll need to provide fast5 files to run the `--nanopolish` pipeline. The `--medaka` pipeline doesn't have this requirement so should work just fine with just fastq files. This is documented in the [`--help`](https://github.com/connor-lab/ncov2019-artic-nf/blob/e77feedba8ac34c526ed17bb3c111c88f9cb4c7d/modules/help.nf#L29), but it seems I've missed documenting it somewhere else so please point me to where I've missed this so that I can correct it!

**Comment by ctr26** [comment]
"Use --nanopolish or --medaka to run these workflows. --basecalled_fastq should point to a directory created by guppy_basecaller (if you ran with no barcodes), or guppy_barcoder (if you ran with barcodes). It is imperative that the following guppy_barcoder command be used for demultiplexing:"

From the readme it doesn't explicitly state this

`nextflow run main.nf -profile docker --nanopolish --prefix "ena"  --fast5_pass ... `

nanopolish will run with a empty fast5_pass directory (would be good if it returned an error and asked if the user wanted to use medaka instead)

I should've read the help carefully though because it is quite obvious and I'm not sure how I missed it :

"--fast5_pass            Directory containing fast5 files - usually fast5_pass. NOT REQUIRED FOR MEDAKA WORKFLOW."
