### ISSUE TITLE
Add guppy_barcoder

### ISSUE THREAD

**Issue by iferres** [connor-lab/ncov2019-artic-nf#9]
Hi, excellent work done here! I was doing exactly this when I found you were actively developing this last version of the Artic pipeline in nextflow (much more professionally done here).

I was wondering if it is possible to add guppy to the singularity image, and to add the guppy_barcoder step at the beginning. 

Thanks

**Comment by m-bull** [comment]
Thanks @iferres :)

I'm reluctant to add any guppy stuff to the pipeline/images, because guppy is behind the ONT sign-in wall. I guess I could add the .debs to the containers directly, but they wouldn't be available in the `conda` profile then.

I think most people are doing live basecalling anyway now, we certainly are. You can also do live demultiplexing with guppy, but make sure you check this [ARTIC thread](https://community.artic.network/t/ont-enabling-require-barcodes-both-ends-for-real-time-basecalling/70) out for advice on enabling `--require_barcodes_both_ends`.

The output from the live basecalling/demuxing goes straight into this pipeline, so hopefully that helps!

**Comment by iferres** [comment]
I understand, no problem. Thanks for your time! I'll keep watching your progress on this repo.
